[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888

# Note: VITE_GEMINI_API_KEY must be set in Netlify Dashboard
# Go to: Site Configuration > Environment Variables
# Make sure it's available for "Production" and "Build" contexts

[[redirects]]
  from = "/api/gemini/home-coach"
  to = "/.netlify/functions/home-coach"
  status = 200

[[redirects]]
  from = "/api/gemini/coach-text"
  to = "/.netlify/functions/coach-text"
  status = 200

[context.production]
  [[context.production.redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
